import { Router } from "express";
import { adminRoutes } from "./admin.routes.js";
import { aiRoutes } from "./ai.routes.js";
import { accessibilityRoutes } from "./accessibility.routes.js";
import { authRoutes } from "./auth.routes.js";
import { assignmentsRoutes } from "./assignments.routes.js";
import { badgesRoutes } from "./badges.routes.js";
import { checklistsRoutes } from "./checklists.routes.js";
import { collaborationRoutes } from "./collaboration.routes.js";
import { announcementsRoutes } from "./announcements.routes.js";
import { assessmentsRoutes } from "../modules/assessments/assessments.routes.js";
import { attemptsRoutes } from "../modules/assessments/attempts.routes.js";
import { externalRoutes } from "./external.routes.js";
import { eventsRoutes } from "./events.routes.js";
import { attendanceRoutes } from "./attendance.routes.js";
import { leaderboardRoutes } from "./leaderboard.routes.js";
import { learningPathRoutes } from "./learning-path.routes.js";
import { lessonsRoutes } from "./lessons.routes.js";
import { modulesRoutes } from "./modules.routes.js";
import { notesRoutes } from "./notes.routes.js";
import { onboardingRoutes } from "./onboarding.routes.js";
import { parentRoutes } from "./parent.routes.js";
import { progressRoutes } from "./progress.routes.js";
import { quizzesRoutes } from "./quizzes.routes.js";
import { resourcesRoutes } from "./resources.routes.js";
import { searchRoutes } from "./search.routes.js";
import { studyRoutes } from "./study.routes.js";
import { subjectsRoutes } from "./subjects.routes.js";
import { translateRoutes } from "./translate.routes.js";
import { userModulesRoutes } from "./user-modules.routes.js";
import { preferencesRoutes } from "./preferences.routes.js";
import { pointsRoutes } from "./points.routes.js";
import { challengesRoutes } from "./challenges.routes.js";
import studentRoutes from "./student.routes.js";
import tutorRoutes from "./tutor.routes.js";
import parentStudentRoutes from "./parent-student.routes.js";
import moduleAssignmentsRoutes from "./module-assignments.routes.js";
import moduleUnlockRoutes from "./module-unlock.routes.js";
import progressRbacRoutes from "./progress-rbac.routes.js";
import quizzesRbacRoutes from "./quizzes-rbac.routes.js";
import { questionBankRoutes } from "../modules/questions/question-bank.routes.js";
import { curriculumRoutes } from "./curriculum.routes.js";
import { nscPapersRoutes } from "../modules/nsc-papers/nsc-papers.routes.js";
import { messagingRoutes } from "./messaging.routes.js";
import { timetableRoutes } from "./timetable.routes.js";
import { analyticsRoutes } from "./analytics.routes.js";
import { educationRoutes } from "./education.routes.js";
import { subjectResourcesRoutes } from "./subject-resources.routes.js";

const router = Router();

router.use("/auth", authRoutes);
router.use("/onboarding", onboardingRoutes);
router.use("/user-modules", userModulesRoutes);
router.use("/subjects", subjectsRoutes);
router.use("/modules", modulesRoutes);
router.use("/lessons", lessonsRoutes);
router.use("/assignments", assignmentsRoutes);
router.use("/resources", resourcesRoutes);
router.use("/quizzes", quizzesRoutes);
router.use("/assessments", assessmentsRoutes);
router.use("/attempts", attemptsRoutes);
router.use("/checklists", checklistsRoutes);
router.use("/badges", badgesRoutes);
router.use("/ai", aiRoutes);
router.use("/study", studyRoutes);
router.use("/announcements", announcementsRoutes);
router.use("/events", eventsRoutes);
router.use("/attendance", attendanceRoutes);
router.use("/progress", progressRoutes);
router.use("/search", searchRoutes);
router.use("/admin", adminRoutes);
router.use("/notes", notesRoutes);
router.use("/learning-path", learningPathRoutes);
router.use("/leaderboard", leaderboardRoutes);
router.use("/accessibility", accessibilityRoutes);
router.use("/external", externalRoutes);
router.use("/collaboration", collaborationRoutes);
router.use("/translate", translateRoutes);
router.use("/parent", parentRoutes);
router.use("/preferences", preferencesRoutes);
router.use("/points", pointsRoutes);
router.use("/challenges", challengesRoutes);
router.use("/student", studentRoutes);
router.use("/tutor", tutorRoutes);
router.use("/question-bank", questionBankRoutes);
router.use("/curriculum", curriculumRoutes);
router.use("/nsc-papers", nscPapersRoutes);
router.use("/messages", messagingRoutes);
router.use("/timetable", timetableRoutes);
router.use("/analytics", analyticsRoutes);
router.use("/education", educationRoutes);
router.use("/subject-resources", subjectResourcesRoutes);

// RBAC-enabled routes (these routers already define their full paths, e.g. `/parents/...`)
// so we mount them at the API root to avoid double-prefixing `/api/api/...`.
router.use(parentStudentRoutes);
router.use(moduleAssignmentsRoutes);
router.use(moduleUnlockRoutes);
router.use(progressRbacRoutes);
router.use(quizzesRbacRoutes);

export { router };
